Modified yaml files to recognize optional from_deployment_setting.
QuickenLoans/circleci-server-orbs pull request #4
Opened 2021-03-01 22:19 UTC by mfriedberg01

## :rotating_light: Overview
Modified the build.yml and publish.yml to accept the additional from_deployment_setting parameter.

2021-03-02 18:13 UTC, skluck requested changes

2021-03-02 18:13 UTC, skluck commented on hal/jobs/build.yml
> +        description: 'ID of another deployment. Inherit saved parameters, secrets, and other settings from this deployment setting.'
Language isn't very clear. whats meant by "another deployment"?

Should that be `ID of the deployment setting to use to import settings into this job. Inherit ...`

2021-03-02 18:13 UTC, skluck commented on hal/jobs/build.yml
> +                        <<# parameters.from_deployment_setting >> --from_deployment_setting  << parameters.from_deployment_setting >><</parameters.from_deployment_setting >>
this wouldn't run because its not part of the above command.

It would be the equivalent of
```
publish-build-to-hal --environment myenv
--from_deployment_setting abc
```
its 2 separate commands. You need `\` on the preceding line to escape the newline so it stays part of the same shell command.

2021-03-02 18:13 UTC, skluck commented on hal/jobs/build.yml
> +                        <<# parameters.from_deployment_setting >> --from_deployment_setting  << parameters.from_deployment_setting >><</parameters.from_deployment_setting >>
Also update the flag to `--from-setting` here.

`<<# myval >><</ myval>` is technically for bool values only, I am not really sure why it was used or if it works as intended for the parameters.arguments case above it.

see more: https://circleci.com/docs/2.0/reusing-config/?section=configuration#boolean

2021-03-02 18:42 UTC, mfriedberg01 commented on hal/jobs/build.yml
> +        description: 'ID of another deployment. Inherit saved parameters, secrets, and other settings from this deployment setting.'
I fixed this in the latest push @skluck

2021-03-10 17:29 UTC, skluck approved these changes

2021-03-10 17:29 UTC, merged